name: WebAssembly build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
        SDK_VERSION: 3.1.57.2bi
        SDK_ARCHIVE: python3.12-wasm-sdk-Ubuntu-22.04.tar.lz4
        SDKROOT: /opt/python-wasm-sdk
        SYS_PYTHON: /usr/bin/python3

    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 1

    - name: install python-wasm-sdk for wasi+prebuilts
      run: |
        sudo apt-get install -y lz4 wget pv bash
        echo https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE
        curl -sL --retry 5 https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE | tar xvP --use-compress-program=lz4 | pv -p -l -s 24400 >/dev/null
        curl https://wasmtime.dev/install.sh -sSf | bash
        mkdir -p /opt/python-wasm-sdk/wasisdk/bin
        mv -vf $(find $HOME/|grep /wasmtime$) /opt/python-wasm-sdk/wasisdk/bin/

      working-directory: /


    - name: apply patchwork
      run: |
        chmod +x wasm-build.sh
        bash ./wasm-build.sh patchwork


    - name: Build WASM with emsdk
      run: |
        bash ./wasm-build.sh

